### ISSUE TITLE
Instructions to open the CmTrace

### ISSUE THREAD

**Issue by OHedeby** [MarkusBux/CmTrace#2]
Hey,

I like the way how you have developed it, it looks clean and nice from the picture. 
I ended up in a situation where I got myself a MacOS too and have ended up in a situation where I have ask, how do I open this project/application?

**Comment by MarkusBux** [comment]
Hello @OHedeby ,

you can just download the ZIP from the latest preview release. https://github.com/MarkusBux/CmTrace/releases/tag/0.5-Preview

Extract it and open the application.
