### ISSUE TITLE
Won't Parse File

### ISSUE THREAD

**Issue by khris91** [MarkusBux/CmTrace#3]
Loaded .5 preview and when I try to load a .log file that's 8kb it sits at "Parsed files: 0/1"

![image](https://github.com/MarkusBux/CmTrace/assets/19496544/66f23a86-c5f2-4ab7-996d-ad75c3bbae60)

**Comment by MarkusBux** [comment]
Hi @khris91 ,

thank you for reporting this issue. Can you please provide the sample data that does not load?

**Comment by MarkusBux** [comment]
Hi @khris91 ,

please try https://github.com/MarkusBux/CmTrace/releases/tag/0.6-preview. Maybe this already fixes your issue

**Comment by khris91** [comment]
That one worked! Thank you!
